### ISSUE TITLE
Base image

### ISSUE THREAD

**Issue by gschrader** [wscherphof/oracle-xe-11g-r2#1]
Any chance of releasing the Dockerfile for wscherphof/oracle-linux-7 as well?  I've tried installing using a centos base image and also an upgraded centos to OEL image but I ran into issues with readonly sysctl values so I'm curious how you worked around that.

**Comment by wscherphof** [comment]
Since it's a base image, there isn't really a Dockerfile for that.

I did something like http://docs.oracle.com/cd/E52668_01/E54669/html/ol7-config-os-containers.html#ol7-start-containers

Combined with https://docs.docker.com/reference/commandline/cli/#import

Much like https://blogs.oracle.com/wim/entry/oracle_linux_containers

**Comment by gschrader** [comment]
Thank you for the information, that makes sense.
